create table SeasonStats (
	SeasonStatsId int primary key identity(1,1),
    PlayerID int,
    [Year] int,
	TotalPassesCompleted int default 0,
	TotalPassesAttempted int default 0,
    TotalPassingYards int default 0,
    TotalPassingTouchdowns int default 0,
    TotalInterceptionsThrown int default 0,
	TotalRushingAttempts int default 0,
    TotalRushingYards int default 0,
    TotalRushingTouchdowns int default 0,
	TotalPassTargets int default 0,
	TotalReceptions int default 0,
    TotalRecievingYards int default 0,
    TotalRecievingTouchdowns int default 0,
	TotalFieldGoalsAttempted int default 0,
	TotalFieldGoalsMade int default 0,
	foreign key (PlayerID) references Players(PlayerID),
);